service: serverless-restapi
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-2
  lambdaHashingVersion: 20201221
  # apiGateway:
  #   apiKeys:
  #     - free:
  #         - CWUOxnxD1ijHwwZ1CZBzClFD3323AHvf
  #         - ${opt:stage}-CWUOxnxD1ijHwwZ1CZBzClFD3323AHvf
  #   usagePlan:
  #     - free:
  #         quota:
  #           limit: 5000
  #           offset: 2
  #           period: MONTH
  #         throttle:
  #           burstLimit: 200
  #           rateLimit: 100        
functions:
  hello:
    handler: handler.hello
    events:
      - http:
         path: get/hello
         method: get
  create:
    handler: handler.create
    events: 
      - http:
         path: notes
         method: post
         cors: true 
  getOne:
    handler: handler.getOne
    events:
      - http:
         path: notes/{id}
         method: get
         cors: true
  getAll:
    handler: handler.getAll
    events:
      - http:
         path: notes
         method: get
         cors: true
  update:
    handler: handler.update
    events:
     - http:
         path: notes/{id}
         method: put
         cors: true
  delete:
    handler: handler.delete
    events:
     - http:
         path: notes/{id}
         method: delete
         cors: true               
plugins:
- serverless-offline
  #adding the plugin to be able to run the offline emulation     
 
